# Generated by Django 2.0.4 on 2018-07-23 14:50

import datetime
import dice_world.standard
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=64, verbose_name='角色姓名')),
                ('sex', models.SmallIntegerField(default=0, verbose_name='角色性别')),
                ('head', models.ImageField(default='static/resource/character/head/default/no_img.jpg', upload_to='static/resource/character/head/', verbose_name='角色头像')),
                ('detail', models.FileField(upload_to='static/resource/character/detail/', verbose_name='角色资料文件(必须)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('private', models.BooleanField(default=True, verbose_name='私人角色')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_editor', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '游戏角色',
                'verbose_name_plural': '游戏角色',
            },
        ),
        migrations.CreateModel(
            name='GameTxt',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('room_id', models.CharField(max_length=64, unique=True, verbose_name='游戏房间')),
                ('file', models.FileField(max_length=512, upload_to='', verbose_name='游戏记录文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_uploader', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '游戏文本信息',
                'verbose_name_plural': '游戏文本信息',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('type', models.SmallIntegerField(default=0, verbose_name='队伍类型')),
                ('send_msg', models.BooleanField(default=True, verbose_name='允许发言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='队长')),
                ('send_msg', models.BooleanField(default=True, verbose_name='允许发言')),
                ('is_gamer', models.BooleanField(default=True, verbose_name='玩家')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('tag', dice_world.standard.JSONField(blank=True, max_length=127, null=True, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='加入时间')),
                ('login_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_character', to='game_manager.Character', verbose_name='角色')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='game_manager.Group', verbose_name='团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '团队信息',
                'verbose_name_plural': '团队信息',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('pic', models.ImageField(default='static/resource/items/default/no_img.jpg', upload_to='static/resource/game/items/', verbose_name='物品图片')),
                ('name', models.CharField(max_length=127, verbose_name='物品名称')),
                ('detail', models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='物品描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/resource/game/items/', verbose_name='物品资料文件(可选)')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('unique', models.BooleanField(default=False, verbose_name='是否唯一')),
                ('state', models.SmallIntegerField(default=0, verbose_name='物品状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('num', models.CharField(default=dice_world.standard.create_id, max_length=64, unique=True, verbose_name='房间号')),
                ('name', models.CharField(default=time.time, max_length=64, verbose_name='房间名')),
                ('state', models.SmallIntegerField(default=0, verbose_name='房间状态')),
                ('password', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='房间密码')),
                ('sidelines', models.BooleanField(default=False, verbose_name='允许旁观')),
                ('background', models.CharField(blank=True, max_length=256, null=True, verbose_name='游戏背景描述')),
                ('tag', dice_world.standard.JSONField(blank=True, null=True, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm', to=settings.AUTH_USER_MODEL, verbose_name='GM')),
                ('items', models.ManyToManyField(related_name='room_item', to='game_manager.Item', verbose_name='物品列表')),
                ('npcs', models.ManyToManyField(related_name='room_npc', to='game_manager.Character', verbose_name='NPC列表')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.CreateModel(
            name='RoomItemRecord',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_item_record', to='game_manager.Item', verbose_name='物品')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Character', verbose_name='玩家')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Room', verbose_name='房间')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSkillRecord',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Character', verbose_name='玩家')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Room', verbose_name='房间')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='技能名')),
                ('pic', models.ImageField(default='static/resource/skills/default/no_img.jpg', upload_to='static/resource/game/skills/', verbose_name='技能图片')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/resource/game/skills/', verbose_name='技能资料文件(可选)')),
                ('unique', models.BooleanField(default=False, verbose_name='是否独特')),
                ('detail', models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('state', models.SmallIntegerField(default=0, verbose_name='技能状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='任务模组名')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('init_file', models.FileField(upload_to='static/resource/game/tasks/', verbose_name='任务模组文件(必须)')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('state', models.SmallIntegerField(default=0, verbose_name='任务状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
                ('npc', models.ManyToManyField(related_name='task_npc', to='game_manager.Character', verbose_name='剧情人物')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('file', models.FileField(max_length=127, null=True, upload_to='static/resource/game/records/', verbose_name='日志记录')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesk_belong_room', to='game_manager.Room', verbose_name='房间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='game_manager.Task', verbose_name='任务')),
            ],
        ),
        migrations.AddField(
            model_name='roomskillrecord',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_skill_record', to='game_manager.Skill', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='room',
            name='skills',
            field=models.ManyToManyField(related_name='room_skill', to='game_manager.Skill', verbose_name='技能列表'),
        ),
        migrations.AddField(
            model_name='room',
            name='tasks',
            field=models.ManyToManyField(related_name='room_task', to='game_manager.Task', verbose_name='任务列表'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game_manager.Room', verbose_name='所属房间'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='group_player', through='game_manager.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='玩家列表'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
    ]
