# Generated by Django 2.0.4 on 2018-06-27 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game_manager.models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='任务模组名')),
                ('description', models.TextField(verbose_name='描述')),
                ('map', models.ImageField(null=True, upload_to='static/resource/game/maps/', verbose_name='地图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=64, verbose_name='角色姓名')),
                ('sex', models.SmallIntegerField(default=0, verbose_name='角色性别')),
                ('head', models.ImageField(default='static/resource/character/head/default/no_img.jpg', upload_to='static/resource/character/head/', verbose_name='角色头像')),
                ('detail', models.FileField(upload_to='static/resource/character/detail/', verbose_name='角色资料文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('private', models.BooleanField(default=True, verbose_name='私人角色')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '游戏角色',
                'verbose_name_plural': '游戏角色',
            },
        ),
        migrations.CreateModel(
            name='GameTxt',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('room_id', models.CharField(max_length=64, unique=True, verbose_name='游戏房间')),
                ('file', models.FileField(upload_to='', verbose_name='游戏记录文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user+', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '游戏文本信息',
                'verbose_name_plural': '游戏文本信息',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('type', models.SmallIntegerField(default=0, verbose_name='队伍类型')),
                ('send_msg', models.BooleanField(default=True, verbose_name='允许发言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='队长')),
                ('send_msg', models.BooleanField(default=True, verbose_name='允许发言')),
                ('is_gamer', models.BooleanField(default=True, verbose_name='玩家')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('tag', models.CharField(max_length=127, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='加入时间')),
                ('login_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game_manager.Character', verbose_name='角色')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='game_manager.Group', verbose_name='团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '团队信息',
                'verbose_name_plural': '团队信息',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='物品名称')),
                ('file', models.FileField(upload_to='static/resource/game/items/', verbose_name='物品资料文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('num', models.CharField(default=game_manager.models.create_id, max_length=64, unique=True, verbose_name='房间号')),
                ('name', models.CharField(default=time.time, max_length=64, verbose_name='房间名')),
                ('state', models.SmallIntegerField(default=0, verbose_name='房间状态')),
                ('tag', game_manager.models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm', to=settings.AUTH_USER_MODEL, verbose_name='GM')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='任务模组名')),
                ('init_file', models.FileField(upload_to='static/resource/game/tasks/', verbose_name='任务模组文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.UUIDField(default=game_manager.models.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('file', models.FileField(null=True, upload_to='static/resource/game/records/', verbose_name='日志记录')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room+', to='game_manager.Room', verbose_name='房间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='game_manager.Task', verbose_name='任务')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game_manager.Room', verbose_name='所属房间'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(through='game_manager.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='玩家列表'),
        ),
    ]
