# Generated by Django 2.0.4 on 2018-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='background',
            field=models.CharField(max_length=256, null=True, verbose_name='游戏背景描述'),
        ),
    ]
