# Generated by Django 2.0.4 on 2018-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.SmallIntegerField(default=0, verbose_name='角色性别'),
        ),
    ]
