# Generated by Django 2.0.4 on 2018-07-04 17:37

import datetime
import dice_world.standard
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_manager', '0002_auto_20180703_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkRoom',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('login_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='login_time',
        ),
    ]
