# Generated by Django 2.0.4 on 2018-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_character_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_gamer',
            field=models.BooleanField(default=True, verbose_name='玩家'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='send_msg',
            field=models.BooleanField(default=True, verbose_name='允许发言'),
        ),
    ]
