# Generated by Django 2.0.5 on 2018-06-11 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_auto_20180611_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='send_msg',
            field=models.BooleanField(default=True, verbose_name='允许发言'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间'),
        ),
    ]
