# Generated by Django 2.0.4 on 2018-07-05 10:04

import dice_world.standard
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_auto_20180705_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='房间密码'),
        ),
        migrations.AddField(
            model_name='room',
            name='sidelines',
            field=models.BooleanField(default=False, verbose_name='允许旁观'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.SmallIntegerField(default=1, verbose_name='队伍类型'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='tag',
            field=dice_world.standard.JSONField(blank=True, max_length=127, null=True, verbose_name='标签'),
        ),
    ]
