# Generated by Django 2.0.4 on 2018-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_auto_20180628_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='private',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='item',
            name='private',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
