# Generated by Django 2.0.4 on 2018-07-05 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_auto_20180705_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlinkroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='userlinkroom',
            name='user',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间'),
        ),
        migrations.DeleteModel(
            name='UserLinkRoom',
        ),
    ]
