# Generated by Django 2.0.4 on 2018-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_auto_20180625_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='detail',
            field=models.FileField(upload_to='resource/character/detail/', verbose_name='角色资料文件'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=64, verbose_name='角色姓名'),
        ),
    ]
