# Generated by Django 2.0.4 on 2018-07-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_auto_20180705_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='character',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='character',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_editor', to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='gametxt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_uploader', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='group_player', through='game_manager.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='玩家列表'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_character', to='game_manager.Character', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesk_belong_room', to='game_manager.Room', verbose_name='房间'),
        ),
    ]
