# Generated by Django 2.0.4 on 2018-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0007_auto_20180705_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(default='static/resource/item/pic/default/no_img.jpg', upload_to='static/resource/item/pic/', verbose_name='物品图片'),
        ),
        migrations.AlterField(
            model_name='gametxt',
            name='file',
            field=models.FileField(max_length=512, upload_to='', verbose_name='游戏记录文件'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='队伍类型'),
        ),
    ]
