# Generated by Django 2.0.4 on 2018-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0007_auto_20180625_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='map',
            field=models.ImageField(null=True, upload_to='static/resource/game/maps/', verbose_name='地图'),
        ),
        migrations.AlterField(
            model_name='character',
            name='detail',
            field=models.FileField(upload_to='static/resource/character/detail/', verbose_name='角色资料文件'),
        ),
        migrations.AlterField(
            model_name='character',
            name='head',
            field=models.ImageField(default='static/resource/character/head/default/no_img.jpg', upload_to='static/resource/character/head/', verbose_name='角色头像'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='static/resource/game/items/', verbose_name='物品资料文件'),
        ),
        migrations.AlterField(
            model_name='task',
            name='init_file',
            field=models.FileField(upload_to='static/resource/game/tasks/', verbose_name='任务模组文件'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='file',
            field=models.FileField(null=True, upload_to='static/resource/game/records/', verbose_name='日志记录'),
        ),
    ]
