# Generated by Django 2.0.4 on 2018-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0008_auto_20180709_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
    ]
