# Generated by Django 2.0.5 on 2018-07-15 20:09

import datetime
import dice_world.standard
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_manager', '0015_auto_20180712_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=127, verbose_name='技能名')),
                ('pic', models.ImageField(default='static/resource/skills/default/no_img.jpg', upload_to='static/resource/game/skills/', verbose_name='技能图片')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_creator', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='room',
            name='areas',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddField(
            model_name='room',
            name='skills',
            field=models.ManyToManyField(related_name='room_skill', to='game_manager.Skill', verbose_name='技能列表'),
        ),
    ]
