# Generated by Django 2.0.5 on 2018-07-15 20:18

import datetime
import dice_world.standard
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0016_auto_20180715_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSkillRecord',
            fields=[
                ('id', models.UUIDField(default=dice_world.standard.create_uuid, primary_key=True, serialize=False, verbose_name='UUID')),
                ('private', models.BooleanField(default=False, verbose_name='是否公开')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Character', verbose_name='玩家')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Room', verbose_name='房间')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_skill_record', to='game_manager.Skill', verbose_name='物品')),
            ],
        ),
    ]
