# Generated by Django 2.0.4 on 2018-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0017_roomskillrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字细节'),
        ),
        migrations.AddField(
            model_name='skill',
            name='detail',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字细节'),
        ),
    ]
