# Generated by Django 2.0.4 on 2018-07-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0018_auto_20180716_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='detail',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='灰字'),
        ),
    ]
