# Generated by Django 2.0.4 on 2018-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0019_auto_20180716_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/resource/game/skills/', verbose_name='技能资料文件(可选)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='detail',
            field=models.FileField(upload_to='static/resource/character/detail/', verbose_name='角色资料文件(必须)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/resource/game/items/', verbose_name='物品资料文件(可选)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='init_file',
            field=models.FileField(upload_to='static/resource/game/tasks/', verbose_name='任务模组文件(必须)'),
        ),
    ]
