# Generated by Django 2.0.5 on 2018-07-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0020_auto_20180716_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='是否独特'),
        ),
    ]
