# Generated by Django 2.0.4 on 2018-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0022_task_npc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='npc',
            field=models.ManyToManyField(to='game_manager.Character', verbose_name='剧情人物'),
        ),
    ]
