# Generated by Django 2.0.4 on 2018-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0023_auto_20180718_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='npc',
            field=models.ManyToManyField(related_name='task_npc', to='game_manager.Character', verbose_name='剧情人物'),
        ),
    ]
