# Generated by Django 2.0.4 on 2018-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0024_auto_20180718_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='file',
            field=models.FileField(max_length=127, null=True, upload_to='static/resource/game/records/', verbose_name='日志记录'),
        ),
    ]
